[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-s3-devkitc-1

build_unflags =
    -D ARDUINO_USB_MODE
    -D ARDUINO_USB_CDC_ON_BOOT

framework = arduino
monitor_speed = 921600
upload_speed = 9600
monitor_filters = esp32_exception_decoder
# build_flags = -DARDUINO_USB_MODE=1
# board_build.partitions = partitions_4MB.csv
board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

board_build.filesystem = littlefs

lib_deps = 
    fastled/FastLED @ ^3.6.0

